services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - dbData:/var/lib/mysql
# Make sure that the login is correct in device later on
volumes:
  dbData:
      driver: local
      driver_opts:
        type: local
        o: bind
        device: ${HOME}/data/dbData