services:

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    networks:
      - lan
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    networks:
      - lan
    env_file: .env
    volumes:
      - dbData:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    networks:
      - lan
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
  
  redis:
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    networks:
      - lan
    volumes:
      - redis:/var/redis-db

# Make sure that the login is correct in device later on
volumes:
  dbData:
      driver: local
      driver_opts:
        type: local
        o: bind
        device: ${HOME}/data/dbData

  wordpress:
      driver: local
      driver_opts:
        type: local
        o: bind
        device: ${HOME}/data/wordpress
  
  redis:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${HOME}/data/redis

networks:
  lan:
    driver: bridge